FROM python:3.11-slim
WORKDIR /app
COPY backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY backend /app/backend
ENV PYTHONPATH=/app
ARG SERVICE_NAME
ENV SERVICE_NAME=${SERVICE_NAME}
CMD sh -c "uvicorn backend.services.${SERVICE_NAME}.app.main:app --host 0.0.0.0 --port ${SERVICE_PORT}"
